Fix java 8 tests
Even while java 8 tests were guarded with "Assume.assumeTrue(isJava(8))"
in `static void beforeClass()`, which would skip the test is the java
version is <= 8, the TimeSerializersTest still failed with e.g.

    java.lang.NoClassDefFoundError: java.time.ZoneId
        at java.lang.J9VMInternals.verifyImpl(Native Method)
        at java.lang.J9VMInternals.verify(J9VMInternals.java:85)
        at java.lang.J9VMInternals.initialize(J9VMInternals.java:162)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:80)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:57)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:539)
        at junit.framework.TestSuite.createTest(TestSuite.java:60)
        at junit.framework.TestSuite.addTestMethod(TestSuite.java:307)
        at junit.framework.TestSuite.addTestsFromTestCase(TestSuite.java:150)
        at junit.framework.TestSuite.<init>(TestSuite.java:129)
        at org.junit.internal.runners.JUnit38ClassRunner.<init>(JUnit38ClassRunner.java:74)
        at org.junit.internal.builders.JUnit3Builder.runnerForClass(JUnit3Builder.java:11)
        at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)

for the ibm jdk 7 or with

    java.lang.NoClassDefFoundError: java/time/ZoneId
        at java.lang.Class.getDeclaredConstructors0(Native Method)
        at java.lang.Class.privateGetDeclaredConstructors(Class.java:2493)
        at java.lang.Class.getConstructors(Class.java:1517)
        at org.junit.runners.model.TestClass.<init>(TestClass.java:47)
        at org.junit.runners.ParentRunner.createTestClass(ParentRunner.java:88)
        at org.junit.runners.ParentRunner.<init>(ParentRunner.java:83)
        at org.junit.runners.BlockJUnit4ClassRunner.<init>(BlockJUnit4ClassRunner.java:65)
        at org.junit.runners.JUnit4.<init>(JUnit4.java:22)

for the oracle jdk 7.

This problem was only caused by the usage of ZoneId (or ZoneOffset, which
extends ZoneId) somewhere in the class and was not caused by other java.time
classes - which is somehow weird.

Therefore excluding tests is changed back to a maven profile which now
excludes "Java8*Test" if running with a java version < 8.