Update to reflectasm-1.08-shaded.
With this the FieldSerializerTest.testDefaultInstantiatorStrategy fails with an IllegalAccessError:

java.lang.IllegalAccessError: tried to access method com.esotericsoftware.kryo.FieldSerializerTest$HasPrivateConstructor.<init>()V from class com.esotericsoftware.kryo.FieldSerializerTest$HasPrivateConstructorConstructorAccess
	at com.esotericsoftware.kryo.FieldSerializerTest$HasPrivateConstructorConstructorAccess.newInstance(Unknown Source)
	at com.esotericsoftware.kryo.Kryo$DefaultInstantiatorStrategy$1.newInstance(Kryo.java:1196)
	at com.esotericsoftware.kryo.Kryo.newInstance(Kryo.java:1067)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.create(FieldSerializer.java:501)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:477)
	at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:767)
	at com.esotericsoftware.kryo.KryoTestCase.roundTripWithStreamFactory(KryoTestCase.java:187)
	at com.esotericsoftware.kryo.KryoTestCase.roundTrip(KryoTestCase.java:62)
	at com.esotericsoftware.kryo.FieldSerializerTest.testDefaultInstantiatorStrategy(FieldSerializerTest.java:325)