Fix javadoc when releasing with java11
Due to changes the release has to be done with java 11.
This now failed during javadoc generation, with e.g.
```
error: package sun.nio.ch is not visible
```